export enum LAYOUT_MAP_MUTATIONS {
    SHOW_UPLOAD_LAYOUT_MAP_POPUP = 'SHOW_UPLOAD_LAYOUT_MAP_POPUP',
    SET_SELECTED_CAMERA_GROUP_ID = 'SET_SELECTED_CAMERA_GROUP_ID',
    SET_CAMERA_GROUP_LIST = 'SET_CAMERA_GROUP_LIST',
    SET_CAMERA_LIST = 'SET_CAMERA_LIST',
    SET_UNASSIGNED_CAMERA_LIST = 'SET_UNASSIGNED_CAMERA_LIST',
    SET_LAYOUT_MAP_DETAIL = 'SET_LAYOUT_MAP_DETAIL',
    SET_CAMERA_COORDINATE_PARAMS = 'SET_CAMERA_COORDINATE_PARAMS',
    SET_LAYOUT_MAP_DETAIL_DATA_FROM_RESPONSE = 'SET_LAYOUT_MAP_DETAIL_DATA_FROM_RESPONSE',
    SET_CAN_EDIT_LAYOUT_MAP = 'SET_CAN_EDIT_LAYOUT_MAP',
    SET_LAYOUT_MAP_FORM = 'SET_LAYOUT_MAP_FORM',
}
