export enum PLAYBACK_MUTATION {
    SET_PLAYBACK_QUERY = 'SET_PLAYBACK_QUERY',
    SET_CAMERA_LIST = 'SET_CAMERA_LIST',
    SET_PLAYBACK_LIST = 'SET_PLAYBACK_LIST',
    SET_PLAYBACK_DETAIL = 'SET_PLAYBACK_DETAIL',
}

export const DEFAULT_LIST_LIMIT = 10000;
